[tool.poetry]
name = "strategy-lab"
version = "0.1.0"
description = "Backtesting and strategy research framework"
authors = ["Your Name <your@email.com>"]

[tool.poetry.dependencies]
python = "^3.11"
polars = "^1.20.0"
asyncpg = "^0.30.0"
holidays = "^0.71"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
